apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: schedulers.k-avy.example.com
  labels:
    samples.knative.dev/release: devel
    knative.dev/crd-install: "true"
spec:
  group: k-avy.example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - script
                - duration
              properties:
                script:
                  type: string
                duration:
                  type: string
  names:
    kind: Scheduler
    plural: schedulers
    singular: scheduler
    shortNames:
      - sch
  scope: Namespaced
